# Generated by Django 4.2 on 2024-02-03 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_alter_user_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrangement', models.CharField(max_length=300, verbose_name='日期安排(文字描述)')),
                ('duration_days', models.IntegerField(verbose_name='活动持续天数')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注(不超过500字)')),
                ('price', models.IntegerField(verbose_name='活动价格')),
                ('need_rent', models.BooleanField(default=False, verbose_name='是否提供租赁雪具服务')),
                ('target_participant_num', models.IntegerField(verbose_name='目标报名人数')),
                ('current_participant_num', models.IntegerField(default=0, verbose_name='当前报名人数')),
                ('release_dt', models.DateTimeField(auto_now_add=True, verbose_name='活动发布时间')),
                ('signup_ddl_d', models.DateField(verbose_name='活动截止报名日期(当天23:59截止报名)')),
                ('registration_status', models.BooleanField(default=True, verbose_name='是否可以报名')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=10, verbose_name='车牌号')),
                ('people_num', models.IntegerField(default=0, verbose_name='人数')),
                ('route', models.CharField(max_length=500, null=True, verbose_name='路线规划')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.activity', verbose_name='活动')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_rent', models.BooleanField(verbose_name='是否租赁')),
                ('bus_time', models.DateTimeField(null=True, verbose_name='上车时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.activity', verbose_name='活动')),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.bus', verbose_name='大巴')),
                ('bus_loc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.school', verbose_name='上车点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='Skiresort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='滑雪场名')),
                ('location', models.CharField(max_length=200, verbose_name='位置')),
            ],
        ),
        migrations.CreateModel(
            name='Rentprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helmet_price', models.IntegerField(verbose_name='头盔单价')),
                ('helmet_deposit', models.IntegerField(verbose_name='头盔押金')),
                ('glasses_price', models.IntegerField(verbose_name='雪镜单价')),
                ('glasses_deposit', models.IntegerField(verbose_name='雪镜押金')),
                ('gloves_price', models.IntegerField(verbose_name='手套单价')),
                ('gloves_deposit', models.IntegerField(verbose_name='手套押金')),
                ('hippad_price', models.IntegerField(verbose_name='护臀单价')),
                ('hippad_deposit', models.IntegerField(verbose_name='护臀押金')),
                ('kneepad_price', models.IntegerField(verbose_name='护膝单价')),
                ('kneepad_deposit', models.IntegerField(verbose_name='护膝押金')),
                ('wrist_price', models.IntegerField(verbose_name='护腕单价')),
                ('wrist_deposit', models.IntegerField(verbose_name='护腕押金')),
                ('snowboard_price', models.IntegerField(verbose_name='雪板单价')),
                ('snowboard_deposit', models.IntegerField(verbose_name='雪板押金')),
                ('skiboots_price', models.IntegerField(verbose_name='雪鞋单价')),
                ('skiboots_deposit', models.IntegerField(verbose_name='雪鞋押金')),
                ('ski_resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.skiresort', verbose_name='滑雪场')),
            ],
        ),
        migrations.CreateModel(
            name='Rentorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_days', models.IntegerField(verbose_name='租赁天数')),
                ('helmet', models.BooleanField(verbose_name='头盔')),
                ('glasses', models.BooleanField(verbose_name='学镜')),
                ('gloves', models.BooleanField(verbose_name='手套')),
                ('hippad', models.BooleanField(verbose_name='护臀')),
                ('kneepad', models.BooleanField(verbose_name='护膝')),
                ('wrist', models.BooleanField(verbose_name='护腕')),
                ('snowboard', models.BooleanField(verbose_name='雪板')),
                ('skiboots', models.BooleanField(verbose_name='雪鞋')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.order', verbose_name='对应活动订单')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.rentprice', verbose_name='价格')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='Bus_boarding_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='途径时间')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.bus', verbose_name='大巴')),
                ('loc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.school', verbose_name='途径点')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='ski_resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.skiresort', verbose_name='滑雪场'),
        ),
    ]
