# Generated by Django 4.2 on 2024-02-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_rename_wrist_rentorder_wristpad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='need_rent',
            field=models.BooleanField(default=False, verbose_name='是否租赁'),
        ),
    ]
