# Generated by Django 4.2 on 2024-02-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_order_need_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentorder',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否有效(活动订单是否付款)'),
        ),
    ]
