# Generated by Django 4.2 on 2024-02-05 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_school'),
        ('activity', '0004_rentorder_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_loc_time',
            name='people_num',
            field=models.IntegerField(default=0, verbose_name='该点上车人数'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.bus', verbose_name='大巴'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bus_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.bus_loc_time', verbose_name='上车时间'),
        ),
        migrations.CreateModel(
            name='Busloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_num', models.IntegerField(default=0, verbose_name='人数')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.activity', verbose_name='活动')),
                ('loc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.school', verbose_name='上车点')),
            ],
        ),
        migrations.AlterField(
            model_name='bus_loc_time',
            name='loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.busloc', verbose_name='途径点'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bus_loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.busloc', verbose_name='大巴'),
        ),
    ]
