# Generated by Django 4.2 on 2024-02-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_bus_loc_time_people_num_alter_order_bus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busloc',
            old_name='people_num',
            new_name='loc_peoplenum',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='people_num',
        ),
        migrations.RemoveField(
            model_name='bus_loc_time',
            name='people_num',
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_peoplenum',
            field=models.IntegerField(default=0, verbose_name='该车总人数'),
        ),
        migrations.AddField(
            model_name='bus_loc_time',
            name='bus_loc_peoplenum',
            field=models.IntegerField(default=0, verbose_name='该点该车上车人数'),
        ),
    ]
