# Generated by Django 4.2 on 2024-02-05 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_area_options_alter_school_options_and_more'),
        ('activity', '0006_rename_people_num_busloc_loc_peoplenum_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': '活动', 'verbose_name_plural': '活动'},
        ),
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': '大巴车', 'verbose_name_plural': '大巴车'},
        ),
        migrations.AlterModelOptions(
            name='bus_loc_time',
            options={'verbose_name': '车-途径点-时间 对应关系', 'verbose_name_plural': '车-途径点-时间 对应关系'},
        ),
        migrations.AlterModelOptions(
            name='busloc',
            options={'verbose_name': '上车点', 'verbose_name_plural': '上车点'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '活动订单', 'verbose_name_plural': '活动订单'},
        ),
        migrations.AlterModelOptions(
            name='rentorder',
            options={'verbose_name': '租赁单', 'verbose_name_plural': '租赁单'},
        ),
        migrations.AlterModelOptions(
            name='rentprice',
            options={'verbose_name': '雪具租赁价格', 'verbose_name_plural': '雪具租赁价格'},
        ),
        migrations.AlterModelOptions(
            name='skiresort',
            options={'verbose_name': '滑雪场', 'verbose_name_plural': '滑雪场'},
        ),
        migrations.AlterUniqueTogether(
            name='busloc',
            unique_together={('activity', 'loc')},
        ),
    ]
