# Generated by Django 4.2 on 2024-02-05 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_alter_activity_options_alter_bus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration_days',
            field=models.IntegerField(verbose_name='持续天数'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='need_rent',
            field=models.BooleanField(default=False, verbose_name='提供租赁雪具服务'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.IntegerField(verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='release_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='signup_ddl_d',
            field=models.DateField(verbose_name='截止报名日期\n(当天23:59截止报名)'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='car_number',
            field=models.CharField(max_length=10, null=True, verbose_name='车牌号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.bus', verbose_name='大巴'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bus_loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.busloc', verbose_name='上车点'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bus_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.bus_loc_time', verbose_name='上车时间'),
        ),
    ]
