# Generated by Django 4.2 on 2024-02-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_alter_bus_loc_time_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='need_rent',
            field=models.BooleanField(default=False, verbose_name='提供租赁'),
        ),
    ]
