# Generated by Django 4.2 on 2024-11-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='target_participant',
            field=models.IntegerField(blank=True, null=True, verbose_name='目标报名人数'),
        ),
    ]
