# Generated by Django 4.2 on 2024-02-04 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentorder',
            old_name='wrist',
            new_name='wristpad',
        ),
        migrations.RenameField(
            model_name='rentprice',
            old_name='wrist_deposit',
            new_name='wristpad_deposit',
        ),
        migrations.RenameField(
            model_name='rentprice',
            old_name='wrist_price',
            new_name='wristpad_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='rentorder',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='是否支付'),
        ),
        migrations.AddField(
            model_name='order',
            name='ordernumber',
            field=models.CharField(default='123456789', max_length=50, unique=True, verbose_name='订单号'),
        ),
        migrations.AddField(
            model_name='rentorder',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='activity.activity', verbose_name='活动'),
        ),
    ]
