# Generated by Django 4.2 on 2024-10-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': '区域', 'verbose_name_plural': '区域'},
        ),
        migrations.AlterModelOptions(
            name='boardingloctemplate',
            options={'verbose_name': '上车点可选范围', 'verbose_name_plural': '上车点可选范围'},
        ),
    ]
