# Generated by Django 4.2 on 2024-11-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activity_target_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytemplate',
            name='leader_notice',
            field=models.TextField(null=True, verbose_name='领队须知'),
        ),
    ]
