# Generated by Django 4.2 on 2024-10-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_area_options_alter_boardingloctemplate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skiresort',
            name='intro',
            field=models.CharField(max_length=11, verbose_name='简介'),
        ),
    ]
