# Generated by Django 4.2 on 2024-10-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_skiresort_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skiresort',
            name='intro',
            field=models.CharField(max_length=25, verbose_name='简介'),
        ),
    ]
