# Generated by Django 4.2 on 2024-11-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_activitytemplate_leader_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='success_departue',
            field=models.BooleanField(default=False, verbose_name='是否成功运行分车系统'),
        ),
    ]
