# Generated by Django 4.2 on 2024-11-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_activity_success_departue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytemplate',
            name='name',
            field=models.CharField(help_text='示例：“翠云山滑雪场两日票” (雪场+天数， 12字以内)', max_length=12, null=True, verbose_name='活动名称'),
        ),
    ]
