# Generated by Django 4.2 on 2024-10-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_skiresort_intro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skiresortpic',
            old_name='gift',
            new_name='skiresort',
        ),
        migrations.AddField(
            model_name='activitytemplate',
            name='name',
            field=models.CharField(help_text='(雪场+天数， 20字以内)', max_length=20, null=True, verbose_name='活动名称'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='intro',
            field=models.CharField(max_length=25, null=True, verbose_name='简介'),
        ),
    ]
