# Generated by Django 4.2 on 2024-10-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_rename_gift_skiresortpic_skiresort_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitytemplate',
            old_name='schedule_full',
            new_name='schedule',
        ),
        migrations.AlterField(
            model_name='activitytemplate',
            name='name',
            field=models.CharField(help_text='示例：“翠云山银河滑雪场两日票” (雪场+天数， 20字以内)', max_length=20, null=True, verbose_name='活动名称'),
        ),
    ]
