# Generated by Django 4.2 on 2024-11-09 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_activitytemplate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytemplate',
            name='name',
            field=models.CharField(help_text='示例：“两日住滑票” (12字以内)', max_length=10, null=True, verbose_name='活动名称'),
        ),
        migrations.AlterField(
            model_name='boardingloctemplate',
            name='busboardloc',
            field=models.CharField(max_length=150, verbose_name='上车点(如：北门)'),
        ),
        migrations.AlterField(
            model_name='boardingloctemplate',
            name='campus',
            field=models.CharField(max_length=150, unique=True, verbose_name='校区'),
        ),
        migrations.AlterField(
            model_name='boardingloctemplate',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.school', verbose_name='学校名称'),
        ),
    ]
