# Generated by Django 4.2 on 2024-10-20 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_rename_schedule_full_activitytemplate_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='原价'),
        ),
    ]
