# Generated by Django 4.2 on 2024-11-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_alter_activitytemplate_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardingloctemplate',
            name='campus',
            field=models.CharField(max_length=150, verbose_name='校区'),
        ),
        migrations.AlterUniqueTogether(
            name='boardingloctemplate',
            unique_together={('school', 'campus', 'busboardloc', 'area')},
        ),
    ]
