# Generated by Django 4.2 on 2024-10-21 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_ticket_original_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='service',
            field=models.CharField(help_text='请使用空格分隔各个服务。可选服务有：滑雪门票 往返车票 酒店住宿 雪具租赁 人身保险', max_length=100, validators=[django.core.validators.RegexValidator('^((滑雪门票|往返车票|酒店住宿|雪具租赁|人身保险) )*(滑雪门票|往返车票|酒店住宿|雪具租赁|人身保险)$', '请使用空格分隔各个服务。可选服务有：滑雪门票 往返车票 酒店住宿 雪具租赁 人身保险')], verbose_name='提供的服务'),
        ),
    ]
