# Generated by Django 4.2 on 2024-11-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_alter_boardingloctemplate_campus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytemplate',
            name='name',
            field=models.CharField(help_text='示例：“金山岭两日住滑票” (12字以内)', max_length=12, null=True, verbose_name='活动票名'),
        ),
        migrations.AlterUniqueTogether(
            name='boardingloctemplate',
            unique_together={('school', 'campus', 'busboardloc')},
        ),
    ]
