# Generated by Django 4.2 on 2024-10-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_alter_ticket_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='from_to',
            field=models.CharField(default='北京海淀 北京平谷', help_text='出发地 目的地，使用空格分隔。示例：“北京 崇礼”', max_length=30, verbose_name='从哪到哪 (from to)'),
        ),
    ]
