# Generated by Django 4.2 on 2024-11-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_alter_activitytemplate_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='target_participant',
            field=models.IntegerField(default=9999, null=True, verbose_name='报名人数上限'),
        ),
    ]
