# Generated by Django 4.2 on 2024-02-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_alter_activity_duration_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordernumber',
            field=models.CharField(max_length=50, unique=True, verbose_name='订单号'),
        ),
    ]
