# Generated by Django 4.2 on 2024-11-20 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_alter_activity_target_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rentprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='雪具名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格（整个活动时间的总价，不分天数）')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='押金')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.activity', verbose_name='活动')),
            ],
            options={
                'verbose_name': '雪具租赁信息',
                'verbose_name_plural': '雪具租赁信息',
                'unique_together': {('activity', 'name')},
            },
        ),
    ]
