# Generated by Django 4.2 on 2024-02-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_alter_order_ordernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_loc_time',
            name='time',
            field=models.DateTimeField(null=True, verbose_name='途径时间'),
        ),
    ]
