# Generated by Django 4.2 on 2024-10-21 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_skiresort_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='from_to',
        ),
    ]
