# Generated by Django 4.2 on 2024-11-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_rentprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='hotel',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='酒店'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='hotel_type',
            field=models.IntegerField(choices=[(0, '不提供分配'), (1, '提供分配')], default=0, verbose_name='住宿类型（是否提供分房服务）'),
        ),
    ]
