# Generated by Django 4.2 on 2024-10-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_remove_activity_from_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='city_name',
            field=models.CharField(max_length=100, null=True, verbose_name='所属城市名称'),
        ),
    ]
