# Generated by Django 4.2 on 2024-10-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_area_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_return_time',
            field=models.TimeField(null=True, verbose_name='返程时间'),
        ),
    ]
