# Generated by Django 4.2 on 2024-10-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_activity_activity_return_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_return_time',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_return_datetime',
            field=models.DateTimeField(null=True, verbose_name='返程集合日期时间'),
        ),
    ]
