# Generated by Django 4.2 on 2024-10-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_remove_activity_activity_return_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_return_datetime',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_return_time',
            field=models.TimeField(null=True, verbose_name='返程集合时间'),
        ),
    ]
