# Generated by Django 4.2 on 2024-10-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0015_remove_activity_activity_return_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_return_loc',
            field=models.CharField(max_length=70, null=True, verbose_name='返程集合位置'),
        ),
    ]
