# Generated by Django 4.2 on 2024-10-25 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0016_activity_activity_return_loc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaBoardingLowerLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_limit', models.IntegerField(verbose_name='下限人数')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.activity', verbose_name='活动')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.area', verbose_name='所在地区')),
            ],
            options={
                'verbose_name': '区域上车下限',
                'verbose_name_plural': '区域上车下限',
            },
        ),
    ]
