# Generated by Django 4.2 on 2024-10-29 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0017_areaboardinglowerlimit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitywxgroup',
            options={'verbose_name': '微信群二维码', 'verbose_name_plural': '微信群二维码'},
        ),
    ]
