# Generated by Django 4.2 on 2024-10-31 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0018_alter_activitywxgroup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='city_name',
            field=models.CharField(max_length=100, verbose_name='所属城市名称'),
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.area', verbose_name='所在地区'),
        ),
    ]
