# Generated by Django 4.2 on 2024-11-02 16:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0019_alter_area_city_name_alter_skiresort_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bustype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_num', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='可承载人数')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='单价')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.activity', verbose_name='活动')),
            ],
            options={
                'verbose_name': '大巴车类型(只支持两种类型)',
                'verbose_name_plural': '大巴车类型(只支持两种类型)',
            },
        ),
    ]
