# Generated by Django 4.2 on 2024-01-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='地区名称'),
        ),
        migrations.AlterField(
            model_name='school',
            name='campus',
            field=models.CharField(max_length=150, unique=True, verbose_name='学校位置(学校名+校区)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='openid',
            field=models.CharField(db_index=True, max_length=28, unique=True, verbose_name='openid'),
        ),
    ]
