# Generated by Django 4.2 on 2024-01-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_area_area_name_alter_school_campus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesstoken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acess_token', models.CharField(max_length=1024, unique=True)),
                ('expire_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(choices=[(0, '男'), (1, '女')], verbose_name='性别'),
        ),
    ]
