# Generated by Django 4.2 on 2024-01-31 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_accesstoken_alter_user_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesstoken',
            old_name='acess_token',
            new_name='access_token',
        ),
    ]
