# Generated by Django 4.2 on 2024-02-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_acess_token_accesstoken_access_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='hight',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='wight',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wxaccount',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(choices=[(0, '男'), (1, '女')], null=True, verbose_name='性别'),
        ),
    ]
