# Generated by Django 4.2 on 2024-02-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_bustype_alter_user_gender_alter_user_height_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bustype',
            options={'verbose_name': '大巴车类型', 'verbose_name_plural': '大巴车类型'},
        ),
    ]
