# Generated by Django 4.2 on 2024-01-29 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100, verbose_name='地区名称')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50, verbose_name='学校名称')),
                ('campus', models.CharField(max_length=150, verbose_name='学校位置(校区)')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.area', verbose_name='所在地区')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=28, unique=True, verbose_name='openid')),
                ('name', models.CharField(max_length=15, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.BooleanField(verbose_name='性别')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('wxaccount', models.CharField(max_length=22, verbose_name='微信号')),
                ('hight', models.IntegerField(null=True, verbose_name='身高(cm)')),
                ('wight', models.IntegerField(null=True, verbose_name='体重(kg)')),
                ('skiboots_size_1', models.IntegerField(null=True, verbose_name='单板雪鞋尺码')),
                ('skiboots_size_2', models.IntegerField(null=True, verbose_name='双板雪鞋尺码')),
                ('snowboard_size_1', models.IntegerField(null=True, verbose_name='单板板长')),
                ('snowboard_size_2', models.IntegerField(null=True, verbose_name='双板板长')),
                ('skipole_size', models.IntegerField(null=True, verbose_name='雪仗长度')),
                ('ski_level', models.IntegerField(choices=[(0, '小白'), (1, '新手'), (2, '走刃'), (3, '大佬')], null=True, verbose_name='滑雪水平')),
                ('ski_style', models.IntegerField(choices=[(0, '基础'), (1, '刻滑'), (2, '平花'), (3, '公园')], null=True, verbose_name='滑雪风格')),
                ('ski_board', models.IntegerField(choices=[(0, '单板'), (1, '双板')], null=True, verbose_name='单板or双板')),
                ('is_student', models.BooleanField(default=False, verbose_name='是否通过学生认证')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.school', verbose_name='学校_id')),
            ],
        ),
    ]
