# Generated by Django 4.2 on 2024-11-03 17:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesstoken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=512)),
                ('expire_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(db_index=True, max_length=28, unique=True, verbose_name='openid')),
                ('name', models.CharField(blank=True, max_length=15, null=True, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('idnumber', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='user/profile/', verbose_name='头像')),
                ('points', models.IntegerField(blank=True, default=0, null=True, verbose_name='积分')),
                ('identity', models.IntegerField(choices=[(0, '普通用户'), (1, '领队')], default=0, verbose_name='身份')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='个人介绍')),
                ('is_student', models.BooleanField(default=False, verbose_name='是否通过学生认证')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('ski_board', models.IntegerField(blank=True, choices=[(0, '单板'), (1, '双板')], null=True, verbose_name='单板or双板')),
                ('ski_level', models.IntegerField(blank=True, choices=[(0, '小白'), (1, '新手'), (2, '走刃'), (3, '大佬')], null=True, verbose_name='滑雪水平')),
                ('ski_favor', models.IntegerField(blank=True, choices=[(0, '基础'), (1, '刻滑'), (2, '平花'), (3, '公园'), (4, '野雪')], null=True, verbose_name='滑雪喜好')),
                ('gender', models.IntegerField(blank=True, choices=[(0, '男'), (1, '女')], null=True, verbose_name='性别')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='身高(cm)')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='体重(kg)')),
                ('foot_length', models.IntegerField(blank=True, null=True, verbose_name='足长(mm)')),
                ('skiboots_size', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(50)], verbose_name='鞋码')),
                ('snowboard_size_1', models.IntegerField(blank=True, null=True, verbose_name='单板板长')),
                ('snowboard_size_2', models.IntegerField(blank=True, null=True, verbose_name='双板板长')),
                ('snowboard_hardness', models.IntegerField(blank=True, null=True, verbose_name='雪鞋硬度')),
                ('skipole_size', models.IntegerField(blank=True, null=True, verbose_name='雪仗长度')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='领队介绍')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='user/profile/', verbose_name='照片')),
                ('leadtimes', models.IntegerField(default=0, verbose_name='参与活动次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '领队',
                'verbose_name_plural': '领队',
            },
        ),
    ]
