# Generated by Django 4.2 on 2024-11-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='school',
            new_name='sch',
        ),
    ]
