# Generated by Django 4.2 on 2024-10-31 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skiboots_size',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(50)], verbose_name='鞋码'),
        ),
    ]
