# Generated by Django 4.2 on 2024-11-03 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_school_user_sch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sch',
            new_name='school',
        ),
    ]
