# Generated by Django 4.2 on 2024-11-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_sch_user_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='手机号'),
        ),
    ]
