# Generated by Django 4.2 on 2024-02-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_hight_user_height_rename_wight_user_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], null=True, verbose_name='性别'),
        ),
    ]
