# Generated by Django 4.2 on 2024-11-09 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_activitytemplate_name'),
        ('user', '0005_alter_leader_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.school', verbose_name='学校'),
        ),
    ]
