# Generated by Django 4.2 on 2024-11-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_leader_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='节省金额'),
        ),
    ]
