# Generated by Django 4.2 on 2024-02-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_area_options_alter_school_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bustype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_num', models.IntegerField(verbose_name='可承载人数')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, '男'), (1, '女')], null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='身高(cm)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ski_board',
            field=models.IntegerField(blank=True, choices=[(0, '单板'), (1, '双板')], null=True, verbose_name='单板or双板'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ski_level',
            field=models.IntegerField(blank=True, choices=[(0, '小白'), (1, '新手'), (2, '走刃'), (3, '大佬')], null=True, verbose_name='滑雪水平'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ski_style',
            field=models.IntegerField(blank=True, choices=[(0, '基础'), (1, '刻滑'), (2, '平花'), (3, '公园')], null=True, verbose_name='滑雪风格'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skiboots_size_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='单板雪鞋尺码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skiboots_size_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='双板雪鞋尺码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skipole_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='雪仗长度'),
        ),
        migrations.AlterField(
            model_name='user',
            name='snowboard_size_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='单板板长'),
        ),
        migrations.AlterField(
            model_name='user',
            name='snowboard_size_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='双板板长'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='体重(kg)'),
        ),
    ]
