# Generated by Django 4.2 on 2024-10-18 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '__first__'),
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=10, null=True, verbose_name='车牌号')),
                ('carry_peoplenum', models.IntegerField(default=0, verbose_name='车已承载人数')),
                ('max_people', models.IntegerField(null=True, verbose_name='车型最大承载人数')),
                ('route', models.CharField(max_length=500, null=True, verbose_name='路线规划')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.activity', verbose_name='活动')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user', verbose_name='领队')),
            ],
            options={
                'verbose_name': '大巴车',
                'verbose_name_plural': '大巴车',
            },
        ),
        migrations.CreateModel(
            name='Bus_boarding_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_peoplenum', models.IntegerField(default=0, verbose_name='该点该车上车人数')),
                ('time', models.DateTimeField(null=True, verbose_name='预计途径时间')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.bus', verbose_name='大巴')),
                ('loc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.boardingloc', verbose_name='途径点')),
            ],
            options={
                'verbose_name': '车-途径点-时间 对应关系',
                'verbose_name_plural': '车-途径点-时间 对应关系',
            },
        ),
        migrations.CreateModel(
            name='Bustype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_num', models.IntegerField(verbose_name='可承载人数')),
            ],
            options={
                'verbose_name': '大巴车类型(只支持两种类型)',
                'verbose_name_plural': '大巴车类型(只支持两种类型)',
            },
        ),
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('go_boarded', models.BooleanField(default=False, verbose_name='去程是否上车')),
                ('return_boarded', models.BooleanField(default=False, verbose_name='返程是否上车')),
                ('completed_steps', models.IntegerField(default=0, verbose_name='已完成步数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('status', models.IntegerField(choices=[(0, '已取消'), (1, '待付款'), (2, '已付款'), (3, '已锁票')], default=1, verbose_name='订单状态')),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.bus', verbose_name='大巴')),
                ('bus_loc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.boardingloc', verbose_name='上车点')),
                ('bus_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.bus_boarding_time', verbose_name='上车时间')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.ticket', verbose_name='票')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '雪票订单',
                'verbose_name_plural': '雪票订单',
            },
        ),
    ]
