# Generated by Django 4.2 on 2024-10-19 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_area_options_alter_boardingloctemplate_options'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='wxgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.activitywxgroup', verbose_name='微信群'),
        ),
    ]
