# Generated by Django 4.2 on 2024-11-10 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_leaderitinerary_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='leader',
        ),
    ]
