# Generated by Django 4.2 on 2024-10-19 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('order', '0002_ticketorder_wxgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='car_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='车牌号'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='carry_peoplenum',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='车已承载人数'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.user', verbose_name='领队'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='route',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='路线规划'),
        ),
    ]
