# Generated by Django 4.2 on 2024-11-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_bus_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='go_finished',
            field=models.BooleanField(default=False, verbose_name='去程是否完成'),
        ),
        migrations.AddField(
            model_name='bus',
            name='return_finished',
            field=models.BooleanField(default=False, verbose_name='返程是否完成'),
        ),
        migrations.AddField(
            model_name='bus_boarding_time',
            name='go_finished',
            field=models.BooleanField(default=False, verbose_name='去程是否完成'),
        ),
    ]
