# Generated by Django 4.2 on 2024-10-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_bus_car_number_alter_bus_carry_peoplenum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='司机手机号'),
        ),
    ]
