# Generated by Django 4.2 on 2024-10-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_bus_driver_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketorder',
            name='status',
            field=models.IntegerField(choices=[(0, '已取消(交易关闭)'), (1, '待付款'), (2, '已付款'), (3, '已锁票'), (4, '发起退款'), (5, '已退款')], default=1, verbose_name='订单状态'),
        ),
    ]
