# Generated by Django 4.2 on 2024-11-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_bus_go_finished_bus_return_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='ski_finished',
            field=models.BooleanField(default=False, verbose_name='滑雪是否完成'),
        ),
    ]
