# Generated by Django 4.2 on 2024-11-20 10:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_saved_money'),
        ('activity', '0010_rentprice'),
        ('order', '0005_bus_ski_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='cost_rent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='租赁费用'),
        ),
        migrations.CreateModel(
            name='Rentorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='租赁天数')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ticketorder', verbose_name='对应活动订单')),
                ('rent_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.rentprice', verbose_name='租赁项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '租赁单',
                'verbose_name_plural': '租赁单',
            },
        ),
    ]
