# Generated by Django 4.2 on 2024-11-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_ticketorder_cost_rent_rentorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='cost_ticket',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='购票费用'),
        ),
    ]
