# Generated by Django 4.2 on 2024-10-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_ticketorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='arrival_time',
            field=models.TimeField(null=True, verbose_name='预计到达雪场时间'),
        ),
    ]
