# Generated by Django 4.2 on 2024-11-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_ticketorder_cost_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketorder',
            name='cost_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='租赁费用'),
        ),
    ]
