# Generated by Django 4.2 on 2024-10-22 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('order', '0007_bus_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.leader', verbose_name='领队'),
        ),
        migrations.AlterField(
            model_name='bus_boarding_time',
            name='time',
            field=models.TimeField(null=True, verbose_name='预计途径时间'),
        ),
    ]
