# Generated by Django 4.2 on 2024-10-22 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_area_city_name'),
        ('order', '0008_alter_bus_leader_alter_bus_boarding_time_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketorder',
            name='bus_loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.boardingloc', verbose_name='上车点'),
        ),
    ]
