# Generated by Django 4.2 on 2024-10-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_ticketorder_bus_loc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='max_people',
            field=models.IntegerField(help_text='实际最大承载人数-工作人员数', null=True, verbose_name='车型最大承载人数'),
        ),
    ]
