# Generated by Django 4.2 on 2024-10-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_bus_max_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketorder',
            name='completed_steps',
            field=models.IntegerField(default=0, help_text='未使用教程为0，处于第1步为1，完成第1步为2', verbose_name='已完成步数'),
        ),
    ]
