# Generated by Django 4.2 on 2024-10-29 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_ticketorder_completed_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='实付款'),
        ),
    ]
