# Generated by Django 4.2 on 2024-10-31 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_ticketorder_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='pay_time',
            field=models.DateTimeField(null=True, verbose_name='付款时间'),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='ticket_checked',
            field=models.BooleanField(default=False, verbose_name='是否完成验票'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='实付款'),
        ),
    ]
