# Generated by Django 4.2 on 2024-10-31 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0019_alter_area_city_name_alter_skiresort_area'),
        ('user', '0003_alter_user_skiboots_size'),
        ('order', '0013_ticketorder_pay_time_ticketorder_ticket_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketorder',
            name='return_boarded',
            field=models.BooleanField(default=False, verbose_name='返程是否上车（订单是否已完成）'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='status',
            field=models.IntegerField(choices=[(0, '已取消(交易关闭)'), (1, '待付款'), (2, '已付款'), (3, '已锁票'), (4, '发起退款中'), (5, '已退款'), (6, '删除')], default=1, verbose_name='订单状态'),
        ),
        migrations.CreateModel(
            name='LeaderItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.activity', verbose_name='活动')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.bus', verbose_name='大巴')),
                ('bus_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.boardingloc', verbose_name='上车点')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.leader', verbose_name='领队')),
            ],
            options={
                'verbose_name': '领队行程',
                'verbose_name_plural': '领队行程',
            },
        ),
    ]
