# Generated by Django 4.2 on 2024-11-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_ticketorder_return_boarded_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bustype',
        ),
    ]
